#!/bin/bash

title="Without args"

pwd=`pwd`

testA=$(lib/bin/automated)
args=${@}
argsChar='${@}'

if [ "$args" == "$testA$argsChar" ]
then
  echo "SUCCESS: ${title}"
  exit 0
else
  echo "FAIL: ${title}"
  exit 1
fi
