version: 2
jobs:
  build:
    docker:
      - image: node:10.6.0
    working_directory: ~/app
    steps:
      - checkout
      - run: apt-get update && apt-get install -y pcregrep
      #- run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - run: yarn test
