version: 2.1

defaults: &defaults
  working_directory: ~/repo

  docker:
    - image: circleci/node:14.17.5
      auth:
        username: $DOCKERHUB_USER
        password: $DOCKERHUB_PASSWORD

jobs:
  build:
    <<: *defaults

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: yarn

      - run: yarn nps build

      - run: yarn nps test-ci

      - persist_to_workspace:
          root: ~/repo
          paths:
            - .

  publish:
    <<: *defaults

    steps:
      - attach_workspace:
          at: ~/repo

      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/repo/.npmrc

      - run: npm publish --access public

workflows:
  primary:
    jobs:
      - build:
          context:
            - production

      - publish:
          context:
            - production
          requires:
            - build
          filters:
            branches:
              only: main
