version: 2.1

defaults: &defaults
  working_directory: ~/repo

  docker:
    - image: cimg/node:14.17.5

      auth:
        username: $DOCKERHUB_USER
        password: $DOCKERHUB_PASSWORD

jobs:
  build:
    <<: *defaults

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}-{{ checksum "example/package.json" }}
            - v1-dependencies-

      - run: yarn

      - run: yarn nps install-example-deps

      - run: yarn nps build

      - setup_remote_docker:
          version: 20.10.11

      - run:
          background: true
          command: cd example && yarn automated storybook

      - run: yarn nps test-ci

      - store_artifacts:
          path: ~/repo/example/tmp/automated

      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}-{{ checksum "example/package.json" }}
          paths:
            - ~/repo/node_modules
            - ~/repo/example/node_modules

      - persist_to_workspace:
          root: ~/repo
          paths:
            - .

  publish:
    <<: *defaults

    steps:
      - attach_workspace:
          at: ~/repo

      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/repo/.npmrc

      - run: npm publish --access public

workflows:
  primary:
    jobs:
      - build:
          context:
            - production

      - publish:
          context:
            - production
          requires:
            - build
          filters:
            branches:
              only: main
