version: 2.1

jobs:
  context: production
  
  build:

    working_directory: ~/repo

    machine:
      image: ubuntu-2004:202111-02

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}-{{ checksum "example/package.json" }}
            - v1-dependencies-

      - run: yarn

      - run:
          name: Fix permissions
          command: chmod -R 777 ~/repo

      - run: yarn nps install-example-deps

      - run: yarn nps build

      - run:
          background: true
          command: cd example && yarn automated storybook

      - run: yarn wait-on http-get://localhost:3144

      - run:
          name: Test
          command: yarn nps test-ci
          environment:
            AUTOMATED_JEST_VISUAL_REGRESSION_REQUIRED: 1

      - run: cd example && yarn automated storybook-build

      - store_artifacts:
          path: ~/repo/example/tmp/automated

      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}-{{ checksum "example/package.json" }}
          paths:
            - ~/repo/node_modules
            - ~/repo/example/node_modules

      - run:
          name: Publish
          command: |
            if [ $CIRCLE_BRANCH = "main" ]; then
              echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/repo/.npmrc;
              npm publish --access public;

              docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASSWORD;
              yarn nps docker-publish;
            fi
