version: 2.1

jobs:
  build:
    docker:
      - image: circleci/nodejs:14.17.5
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run: echo "this is the build job"

  test:
    docker:
      - image: circleci/nodejs:14.17.5
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run: echo "this is the test job"

workflows:
  build_and_test:
    jobs:
      - build:
          context:
            - production
      - test:
          context:
            - production
