import path from 'path';
import fs from 'fs';
import aptDeps from './apt-deps';
import { execSync, spawnSync } from 'child_process';

const dockerfileDirPath = path.join(__dirname, '../../dist');

const dockerfileFilePath = path.join(dockerfileDirPath, 'Dockerfile');

const content = [
  '# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.',
  '\n\n',
  'FROM cimg/node:14.17.5',
  '\n\n',
  'RUN sudo apt-get update',
  '\n\n',
  `RUN sudo apt install ${aptDeps.join(' ')}`,
  '\n\n',
  'COPY main /home/circleci/project ',
  // '\n\n',
  // 'EXPOSE 3144',
  // '\n\n',
  // 'CMD ["/bin/sh"]',
].join('');

execSync(`mkdir -p ${dockerfileDirPath}`);

fs.writeFileSync(dockerfileFilePath, content);
